language: python
python:
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"
  - "3.5-dev"
  - "nightly"

install: 
  - python python/setup.py install

script: python -m unittest discover python/planout/test
